# This is a basic workflow to help you get started with Actions
name: CI/CD Deploy to Firebase Hosting on merge
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
        - my-stock-slack-pwa2
  pull_request:
    branches:
        - my-stock-slack-pwa2
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
            repoToken: '${{ secrets.GITHUB_TOKEN }}'
            firebaseServiceAccount: '${{ secrets.FIREBASE_AUDIO_TOKEN}}'
            channelId: live
            projectId: mymusicplayers
            target: my-slack-pwa
        env:
            FIREBASE_CLI_EXPERIMENTS: webframeworks
